media:
  input: assets/images
  output: /tuannguyen-batdongsan/assets/images

content:
  - name: properties
    label: Bất động sản
    type: collection
    path: content/properties
    format: yaml

    view:
      primary: title

    fields:
      - name: title
        label: Tiêu đề
        type: string
        required: true

      - name: price
        label: Giá
        type: string
