name: Facebook Auto Post

on:
  workflow_dispatch:

jobs:
  post-to-facebook:
    runs-on: ubuntu-latest

    steps:
      - name: Test Facebook Page Access Token
        env:
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
        run: |
          response=$(curl -s -G \
            "https://graph.facebook.com/v23.0/me" \
            --data-urlencode "fields=id,name" \
            --data-urlencode "access_token=$FACEBOOK_PAGE_ACCESS_TOKEN")

          echo "$response"
